DataBaseHelper/Controllers/DataBaseController.cs
using DataBaseHelper.Common;
using DBH.BLLProvider.MainBLL;
using DBH.BLLService.MainBLL;
using DBH.BLLServiceProvider.MainBLL;
using DBH.Core;
using DBH.Core.Setting;
using DBH.DALProvider.MainDAL;
using DBH.Models.Common;
using DBH.Models.Config;
using DBH.Models.Entitys;
using DBH.Models.EntityViews;
using DBH.Utils.Helper;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using System.IO;

namespace DataBaseHelper.Controllers
{
    /// <summary>
    /// 主要的控制器文件
    /// </summary>
    public class DataBaseController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IDBHManagerBLLProvider _DBHManagerBLLProvider;
        private readonly ISqlServerManagerBLLProvider _sqlServerManagerBLLProvider;
        private readonly IMySqlManagerBLLProvider _mySqlManagerBLLProvider;
        private readonly IOptionsSnapshot<DBHSetting> _dbhSetting;//建议使用IOptionsSnapshot
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IOptionsSnapshot<DBConnectionConfig> _dbConnectionConfig;

        public DataBaseController(ILogger<HomeController> logger, IDBHManagerBLLProvider dBHManagerBLLProvider, ISqlServerManagerBLLProvider sqlServerManagerBLLProvider, IOptionsSnapshot<DBHSetting> dbhSetting, IWebHostEnvironment webHostEnvironment, JWTHelper jWTHelper, IOptionsSnapshot<DBConnectionConfig> dbConnectionConfig, IMySqlManagerBLLProvider mySqlManagerBLLProvider)
        {
            _logger = logger;
            _DBHManagerBLLProvider = dBHManagerBLLProvider;
            _sqlServerManagerBLLProvider = sqlServerManagerBLLProvider;
            _dbhSetting = dbhSetting;
            _webHostEnvironment = webHostEnvironment;
            _dbConnectionConfig = dbConnectionConfig;
            _mySqlManagerBLLProvider = mySqlManagerBLLProvider;
        }
        #region DataBase 页面
        /// <summary>
        /// 首页，选择服务器页面（默认页面）
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Index()
        {
            IList<FS_ServicesView> listEntity = new List<FS_ServicesView>();
            listEntity = await _DBHManagerBLLProvider.GetServicesConfigListAsync();
            ViewData["listEntity"] = listEntity;
            return View(listEntity);
        }

        /// <summary>
        /// 搜索页，主要的搜索功能的页面，可搜索表、存储过程、表值函数
        /// </summary>
        /// <param name="ID">数据库配置表主键ID</param>
        /// <returns></returns>
        public async Task<IActionResult> Search(int? ID)
        {
            int IDval = 0;
            if (ID.HasValue) IDval = ID.Value;
            FS_ServicesEntity fsServiceEntity = new FS_ServicesEntity();
            if (IDval > 0)
            {
                fsServiceEntity = await _DBHManagerBLLProvider.GetServicesEnvityAsync(IDval);
            }

            string currentDBAddress = "";//当前选择的数据库地址
            string currentDBName = "--";
            if (fsServiceEntity != null && !string.IsNullOrEmpty(fsServiceEntity.ServerAddress))
            {
                currentDBAddress = fsServiceEntity.ServerAddress;
                if (fsServiceEntity.ServerPortNo > 0)
                    currentDBAddress += ":" + fsServiceEntity.ServerPortNo.ToString();
                currentDBName = fsServiceEntity.DataBaseName;
            }
            ViewBag.CurrentDBName = currentDBName;
            ViewBag.CurrentDBAddress = currentDBAddress;
            return View(fsServiceEntity);
        }

        /// <summary>
        ///  视图-弹出框-添加数据库
        /// </summary>
        /// <param name="id">大于0表示编辑</param>
        /// <returns></returns>
        public async Task<IActionResult> _ViewAddDataBase(int? id)
        {
            int databaseIDval = 0;
            if (id.HasValue) databaseIDval = id.Value; else databaseIDval = 0;
            FS_ServicesEntity fsServiceEntity = new FS_ServicesEntity();
            if (databaseIDval > 0)
            {
                fsServiceEntity = await _DBHManagerBLLProvider.GetServicesEnvityAsync(databaseIDval);
            }
            IList<FS_ServiceSourceEntity> listSourceEntity = new List<FS_ServiceSourceEntity>();
            listSourceEntity = await _DBHManagerBLLProvider.GetFSServiceSrouceListAsync();
            ViewData["listEntity"] = listSourceEntity;

            Dictionary<int, string> dictDBconfig = new Dictionary<int, string>();
            Array dbArr = Enum.GetValues(typeof(DBCategory));
            foreach (DBCategory dbCategory in dbArr)
            {
                dictDBconfig.Add((int)dbCategory, dbCategory.ToString());
            }
            ViewData["DBCategory"] = dictDBconfig;

            return View(fsServiceEntity);
        }

        /// <summary>
        /// 获取不同的结果的页面的HTML
        /// </summary>
        /// <param name="id"></param>
        /// <param name="typeID"></param>
        /// <param name="typeName"></param>
        /// <returns></returns>
        public async Task<IActionResult> PartialViewForSearchResult(int? id, int? typeID, string typeName)
        {
            int databaseIDval = 0;
            if (id.HasValue) databaseIDval = id.Value; else databaseIDval = 0;
            FS_ServicesEntity fsServiceEntity = new FS_ServicesEntity();
            if (databaseIDval > 0)
            {
                fsServiceEntity = await _DBHManagerBLLProvider.GetServicesEnvityAsync(databaseIDval);
            }
            if (!typeID.HasValue || string.IsNullOrEmpty(typeName))
            {
                return Content("");
            }
            if (fsServiceEntity == null || fsServiceEntity.ID <= 0 || string.IsNullOrEmpty(fsServiceEntity.ServerAddress) || string.IsNullOrEmpty(fsServiceEntity.DataBaseName))
            {
                return Content("");
            }
            string connectionString = string.Empty;
            //获取连接字符串
            if (fsServiceEntity.ServerType == 1)//SqlServer
                connectionString = _dbConnectionConfig.Value.GetMsSqlConnectionString(fsServiceEntity.ServerAddress, fsServiceEntity.ServerPortNo, fsServiceEntity.DataBaseName, fsServiceEntity.LoginName, fsServiceEntity.LoginPassword);
            else if (fsServiceEntity.ServerType == 2)//MySQL
                connectionString = _dbConnectionConfig.Value.GetMySqlConnectionString(fsServiceEntity.ServerAddress, fsServiceEntity.ServerPortNo, fsServiceEntity.DataBaseName, fsServiceEntity.LoginName, fsServiceEntity.LoginPassword);

            if (fsServiceEntity.ServerType == 1)//SqlServer
            {
                _sqlServerManagerBLLProvider.SetConnectionString(connectionString);
            }
            else if (fsServiceEntity.ServerType == 2)//MySQL
            {
                _mySqlManagerBLLProvider.SetConnectionString(connectionString);
            }

            ViewBag.TypeID = typeID;
            ViewBag.TypeName = typeName;
            ViewData["fsServiceEntity"] = fsServiceEntity;
            SysDataBaseSearchView searchView = new SysDataBaseSearchView()
            {
                DBObjectType = (DBObjectType)(typeID.Value),
                TypeName = (string)typeName
            };
            //根据不同的数据类型，返回不同的页面代码
            if (typeID == (int)DBObjectType.U || typeID == (int)DBObjectType.U_C)
            {

                return View("~/Views/Component/_PartialViewSearchAsTable.cshtml", searchView);
            }
            else if (typeID == (int)DBObjectType.P)
            {
                IList<Definition> listDefinition = await _sqlServerManagerBLLProvider.GetDefinitionsAsync(typeName);
                if (listDefinition != null)
                    searchView.Definition = listDefinition.ToList();
                else
                    searchView.Definition = new List<Definition>();
                return View("~/Views/Component/_PartialViewSearchAsProc.cshtml", searchView);
            }
            else if (typeID == (int)DBObjectType.TF)
            {
                IList<Definition> listDefinition = await _sqlServerManagerBLLProvider.GetDefinitionsAsync(typeName);
                if (listDefinition != null)
                    searchView.Definition = listDefinition.ToList();
                else
                    searchView.Definition = new List<Definition>();
                return View("~/Views/Component/_PartialViewSearchAsTFunc.cshtml", searchView);
            }
            else
            {
                return NotFound("类型错误");
            }
        }

        /// <summary>
        /// 生成C# Class
        /// </summary>
        /// <param name="ID">数据库配置ID</param>
        /// <param name="tableName">表名</param>
        /// <returns></returns>
        public async Task<IActionResult> CreateClass(int? ID, string tableName)
        {
            int databaseIDval = 0;
            if (ID.HasValue) databaseIDval = ID.Value; else databaseIDval = 0;
            FS_ServicesEntity fsServiceEntity = new FS_ServicesEntity();
            if (databaseIDval > 0)
            {
                fsServiceEntity = await _DBHManagerBLLProvider.GetServicesEnvityAsync(databaseIDval);
            }
            if (fsServiceEntity == null || fsServiceEntity.ID <= 0 || string.IsNullOrEmpty(fsServiceEntity.ServerAddress) || string.IsNullOrEmpty(fsServiceEntity.DataBaseName))
            {
                return NotFound("service missing");
            }
            List<string> listClass = new List<string>();
            string connectionString = string.Empty;
            //配置连接字符串
            if (fsServiceEntity.ServerType == 1)//SqlServer
                connectionString = _dbConnectionConfig.Value.GetMsSqlConnectionString(fsServiceEntity.ServerAddress, fsServiceEntity.ServerPortNo, fsServiceEntity.DataBaseName, fsServiceEntity.LoginName, fsServiceEntity.LoginPassword);
            else if (fsServiceEntity.ServerType == 2)//MySQL

DataBaseHelper/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DataBaseHelper</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DataBaseHelper.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DataBaseHelper</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DataBase" asp-action="Index">选择服务器</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - DataBaseHelper - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

DataBaseHelper/Views/Shared/_LayoutMain.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - 数据库工具</title>
    <link rel="icon" href="~/favicon.ico" />
    <link rel="stylesheet" href="~/lib/splitpage/css/normalize.css" />
    <link rel="stylesheet" href="~/lib/splitpage/css/default.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/bootstrap-icons-1.9.1/bootstrap-icons.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/bootstrap-table/css/bootstrap-table.min.css" />
    <link rel="stylesheet" href="~/lib/fonts/css/ali-iconfont.css" />
    <link rel="stylesheet" href="~/lib/layui/css/layui.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DataBaseHelper.styles.css" asp-append-version="true" />
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-myNavColor border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <div class="navbar-collapse fs-6 collapse d-sm-inline-flex justify-content-between">
                    <div class="col-4">
                        <ul class="navbar-nav flex-grow  justify-content-start">
                            <li class="nav-item row">
                                <div class="col">
                                    @*LOGO按钮*@
                                    <a class="navbar-brand d-inline-block nav-link" asp-area="" asp-controller="DataBase" asp-action="Index">
                                        <div class="header_logo_jpg ">
                                            <img src="~/lib/images/logo.png" alt="LOGO" width="auto" height="40" class="img-fluid" />
                                        </div>
                                    </a>
                                </div>
                                <div class="col">
                                    @*选择数据库按钮*@
                                    <a class="nav-link nav-myLink text-light mt-2" asp-area="" asp-controller="DataBase" asp-action="Index">选择数据库</a>
                                </div>
                            </li>
                        </ul>
                    </div>
                    @*顶部导航-[服务器-数据库]展示*@
                    <div class="col-4">
                        <ul class="navbar-nav flex-grow justify-content-center">
                            <li class="nav-item text-light">
                                当前：<span id="current_Server_Title">--</span>
                            </li>
                        </ul>
                    </div>
                    <div class="col-4">
                        <ul class="navbar-nav flex-grow justify-content-end">
                            <li class="nav-item text-light">
                                <button type="button" class="btn btn-outline-light border-0 d-none">导出</button>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" id="masterMain" class="masterMain clearfix pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @Html.Raw(DateTime.Now.Year) - FBW工具
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/layui/layui.js"></script>
    <script src="~/lib/formmaster/jquery.form.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap/bootstrap-table/js/bootstrap-table.min.js"></script>
    <script src="~/js/helper.js"></script>
    <script>
        (function () {
            'use strict'
            var forms = document.querySelectorAll('.needs-validation')
            Array.prototype.slice.call(forms)
                .forEach(function (form) {
                    form.addEventListener('submit', function (event) {
                        if (!form.checkValidity()) {
                            event.preventDefault()
                            event.stopPropagation()
                        }
                        form.classList.add('was-validated')
                    }, false)
                })
        })()
        $(function () {

        })
        var tooltipTriggerList = Array.prototype.slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
        var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
            return new bootstrap.Tooltip(tooltipTriggerEl)
        })
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

DataBaseHelper/Views/Shared/_LayoutNull.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DataBaseHelper</title>
    <link rel="stylesheet" href="~/lib/layui/css/layui.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/bootstrap-icons-1.9.1/bootstrap-icons.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DataBaseHelper.styles.css" asp-append-version="true" />
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/layui/layui.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/formmaster/jquery.form.min.js"></script>
    <script src="~/js/helper.js"></script>
    @*<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script> <!--Jquery验证，比较丑，不使用-->
    <script src="~/lib/jquery-validation/dist/additional-methods.min.js"></script>*@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>